challenges:
  pwn-lottery-ctflearn:
    dir: pwn-lottery
    enabled: true
    deprecated: true
    port: 10005
    flag: flag_ctflearn.txt

  pwn-accumulator-ctflearn:
    dir: pwn-accumulator
    enabled: true
    deprecated: true
    port: 10009
    flag: flag_ctflearn.txt

  pwn-random-malloc-ctflearn:
    dir: pwn-random-malloc
    enabled: true
    deprecated: true
    port: 10017
    flag: flag_ctflearn.txt

  pwn-leak-me-ctflearn:
    dir: pwn-leak-me
    enabled: true
    deprecated: true
    port: 10003
    flag: flag_ctflearn.txt

  pwn-readme-ctflearn:
    dir: pwn-readme
    enabled: true
    deprecated: true
    port: 10007
    flag: flag_ctflearn.txt

  pwn-redirected-ctflearn:
    dir: pwn-redirected
    enabled: true
    deprecated: true
    port: 10018
    flag: flag_ctflearn.txt

  pwn-callsys-ctflearn:
    dir: pwn-callsys
    enabled: true
    deprecated: true
    port: 10021
    flag: flag_ctflearn.txt

  pwn-disabled-service-ctflearn:
    dir: pwn-disabled-service
    enabled: true
    deprecated: true
    port: 10002
    flag: flag_ctflearn.txt

  pwn-banned-bytes-ctflearn:
    dir: pwn-banned-bytes
    enabled: true
    deprecated: true
    port: 10012
    flag: flag_ctflearn.txt

  pwn-buffer-brothers-ctflearn:
    dir: pwn-buffer-brothers
    enabled: true
    deprecated: true
    port: 10023
    flag: flag_ctflearn.txt

  pwn-inspector-gadget-ctflearn:
    dir: pwn-inspector-gadget
    enabled: true
    deprecated: true
    port: 10020
    flag: flag_ctflearn.txt

  pwn-domain-name-resolver-ctflearn:
    dir: pwn-domain-name-resolver
    enabled: true
    deprecated: true
    port: 10004
    flag: flag_ctflearn.txt

  pwn-runner-ctflearn:
    dir: pwn-runner
    enabled: true
    deprecated: true
    port: 10001
    flag: flag_ctflearn.txt

  pwn-positive-challenge-ctflearn:
    dir: pwn-positive-challenge
    enabled: true
    deprecated: true
    port: 10010
    flag: flag_ctflearn.txt

  pwn-two-times-sixteen-ctflearn:
    dir: pwn-two-times-sixteen
    enabled: true
    deprecated: true
    port: 10000
    flag: flag_ctflearn.txt

  pwn-no-more-cookies-ctflearn:
    dir: pwn-no-more-cookies
    enabled: true
    deprecated: true
    port: 10016
    flag: flag_ctflearn.txt

  pwn-cookies-ctflearn:
    dir: pwn-cookies
    enabled: true
    deprecated: true
    port: 10015
    flag: flag_ctflearn.txt

  pwn-slow-bin-ctflearn:
    dir: pwn-slow-bin
    enabled: true
    deprecated: true
    port: 10014
    flag: flag_ctflearn.txt

  pwn-house-ctflearn:
    dir: pwn-house
    enabled: true
    deprecated: true
    port: 10006
    flag: flag_ctflearn.txt

  pwn-theft-ctflearn:
    dir: pwn-theft
    enabled: true
    deprecated: true
    port: 10019
    flag: flag_ctflearn.txt

  pwn-hook-ctflearn:
    dir: pwn-hook
    enabled: true
    deprecated: true
    port: 10024
    flag: flag_ctflearn.txt

  pwn-chain-ctflearn:
    dir: pwn-chain
    enabled: true
    deprecated: true
    port: 10008
    flag: flag_ctflearn.txt

  pwn-glob-ctflearn:
    dir: pwn-glob
    enabled: true
    deprecated: true
    port: 10022
    flag: flag_ctflearn.txt

  pwn-management-ctflearn:
    dir: pwn-management
    enabled: true
    deprecated: true
    port: 10013
    flag: flag_ctflearn.txt

  misc-impossible-equation-ctflearn:
    dir: misc-impossible-equation
    enabled: true
    deprecated: true
    port: 10011
    flag: flag_ctflearn.txt

  pwn-slope-ctflearn:
    dir: pwn-slope
    enabled: true
    deprecated: true
    port: 10025
    flag: flag_ctflearn.txt

  pwn-secret-ctflearn:
    dir: pwn-secret
    enabled: true
    deprecated: true
    port: 10026
    flag: flag_ctflearn.txt

  pwn-school-ctflearn:
    dir: pwn-school
    enabled: true
    deprecated: true
    port: 10027
    flag: flag_ctflearn.txt

  re_misc_file-manager-ctflearn:
    dir: re_misc_file-manager
    enabled: true
    deprecated: true
    port: 10028
    flag: flag_ctflearn.txt

  misc_eraser-ctflearn:
    dir: misc_eraser
    enabled: true
    deprecated: true
    port: 10029
    flag: flag_ctflearn.txt

  ctfguide00:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11000
    flag: flag.txt

  ctfguide01:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11001
    flag: flag.txt

  ctfguide02:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11002
    flag: flag.txt

  ctfguide03:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11003
    flag: flag.txt

  ctfguide04:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11004
    flag: flag.txt

  ctfguide05:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11005
    flag: flag.txt

  ctfguide06:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11006
    flag: flag.txt

  ctfguide07:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11007
    flag: flag.txt

  ctfguide08:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11008
    flag: flag.txt

  ctfguide09:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11009
    flag: flag.txt

  ctfguide10:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11010
    flag: flag.txt

  ctfguide11:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11011
    flag: flag.txt

  ctfguide12:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11012
    flag: flag.txt

  ctfguide13:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11013
    flag: flag.txt

  ctfguide14:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11014
    flag: flag.txt

  ctfguide15:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11015
    flag: flag.txt

  ctfguide16:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11016
    flag: flag.txt

  ctfguide17:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11017
    flag: flag.txt

  ctfguide18:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11018
    flag: flag.txt

  ctfguide19:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11019
    flag: flag.txt

  ctfguide20:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11020
    flag: flag.txt

  ctfguide21:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11021
    flag: flag.txt

  ctfguide22:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11022
    flag: flag.txt

  ctfguide23:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11023
    flag: flag.txt

  ctfguide24:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11024
    flag: flag.txt

  ctfguide25:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11025
    flag: flag.txt

  ctfguide26:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11026
    flag: flag.txt

  ctfguide27:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11027
    flag: flag.txt

  ctfguide28:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11028
    flag: flag.txt

  ctfguide29:
    dir: ctfguide_redirector
    enabled: true
    deprecated: true
    port: 11029
    flag: flag.txt
